### ISSUE TITLE
524 server error

### ISSUE THREAD

**Issue by languagemaniac** [MonkeyMaster64/Reddit-User-Media-Downloader-Public#13]
Hi, I am running Linux Mint 21 and I installed all the required dependencies but I'm still getting this error.

```
sudo docker run -v "~/home/user/reddit/" monkeymaster64/reddit-media-downloader --user *******

Traceback (most recent call last):
  File "reddit-media-downloader.py", line 199, in <module>
    main()
  File "reddit-media-downloader.py", line 182, in main
    get_posts('submission', {**json.loads(args.pushshift_params), 'subreddit':args.subreddit, 'author':args.user}, submission_callback)
  File "reddit-media-downloader.py", line 56, in get_posts
    res.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 524 Server Error:  for url: https://api.pushshift.io/reddit/submission/search?author=******&size=100&before=1672410115
```

Is there anything I can do to make it run or is it a server-side error?

**Comment by drk2259** [comment]
Also having same issue but running on Windows docker desktop. Was working fine before.

**Comment by fdas97** [comment]
Did you ever have any luck figuring this out by chance? I'm a newb to all of this and had it running fine and now all I get is a 522 Server Error everytime


```powershell
docker run -v "D:\Scrape Reddit:/usr/src/app/Reddit-User-Media-Downloader-Public/output" monkeymaster64/reddit-media-downloader --user ****** --limit 10
[Errno 17] File exists: '/usr/src/app/Reddit-User-Media-Downloader-Public/output/******'

Traceback (most recent call last):
  File "reddit-media-downloader.py", line 199, in <module>
    main()
  File "reddit-media-downloader.py", line 180, in main
    get_posts('submission', {**json.loads(args.pushshift_params), 'subreddit':args.subreddit, 'author':args.user}, submission_callback, int(args.limit))
  File "reddit-media-downloader.py", line 56, in get_posts
    res.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 522 Server Error:  for url: https://api.pushshift.io/reddit/submission/search?author=Knottybrooke&size=10&before=1682220363
```

**Comment by languagemaniac** [comment]
> Did you ever have any luck figuring this out by chance? I'm a newb to all of this and had it running fine and now all I get is a 522 Server Error
> ``` 

I switched to other media downloader, can't remember which, but I do remember the other one worked, sorry I can't be more specific

**Comment by TylersApps** [comment]
This probably has something to do with Reddit's crackdown on API access. This repo was last updated 3 years ago and Reddit's policy update was late last year.

Unfortunately, this probably won't ever be fixable.
