### ISSUE TITLE
Doesn't run any more

### ISSUE THREAD

**Issue by jayqc1027** [MonkeyMaster64/Reddit-User-Media-Downloader-Public#18]
Hi, I'm getting this error on running it on docker and have not been able to fix the issue

[Errno 17] File exists: '/usr/src/app/Reddit-User-Media-Downloader-Public/output/Lydiagh0st'
Traceback (most recent call last):
  File "reddit-media-downloader.py", line 199, in <module>
    main()
  File "reddit-media-downloader.py", line 180, in main
    get_posts('submission', {**json.loads(args.pushshift_params), 'subreddit':args.subreddit, 'author':args.user}, submission_callback, int(args.limit))
  File "reddit-media-downloader.py", line 56, in get_posts
    res.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.pushshift.io/reddit/submission/search?author=Lydiagh0st&size=100&before=1701661767

Thanks

**Comment by TylersApps** [comment]
This probably has something to do with Reddit's crackdown on API access. This repo was last updated 3 years ago and Reddit's policy update was late last year.
